import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  background: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuBackground: {
    backgroundColor: 'black',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    width: '85%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  form: {
    width: '100%',
    padding: 20,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  welcome: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '600',
    letterSpacing: 2,
    marginBottom: 30,
  },
  label: {
    alignSelf: 'flex-start',
    color: '#fff',
    fontWeight: '600',
    letterSpacing: 1,
    marginBottom: 8,
  },
  input: {
    width: '100%',
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#00ff00',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#fff',
  },
  button: {
    marginTop: 30,
    backgroundColor: '#00ff00',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 6,
  },
  buttonText: {
    color: '#000',
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  success: {
    color: '#fff',
    marginBottom: 10,
  },
  loggedContainer: {
    alignItems: 'center',
  },
  patioContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 20,
  },
  patioTitle: {
    color: '#C6F6D5',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 1,
    marginBottom: 30,
    marginTop: -60,
    textAlign: 'center',
  },
  patioCodeInputSingle: {
    width: 160,
    height: 50,
    backgroundColor: '#7ED957',
    borderRadius: 8,
    marginBottom: 30,
    textAlign: 'center',
    fontSize: 24,
    color: '#222',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    elevation: 2,
    letterSpacing: 6,
  },
  patioButton: {
    backgroundColor: '#444',
    paddingVertical: 10,
    paddingHorizontal: 40,
    borderRadius: 8,
    marginTop: 10,
    elevation: 2,
  },
  patioButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  menuContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 32,
  },
  menuContainerCustom: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  menuButtonLarge: {
    width: 270,
    height: 80,
    borderWidth: 1.5,
    borderColor: '#57E957',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 32,
    backgroundColor: 'transparent',
  },
  menuButtonLargeText: {
    color: '#57E957',
    fontWeight: '600',
    fontSize: 15,
    letterSpacing: 1,
    textAlign: 'center',
  },
  menuRowButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
  },
  menuButtonGreen: {
    width: 110,
    height: 90,
    backgroundColor: '#57E957',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  menuButtonGreenText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 13,
    letterSpacing: 1,
    textAlign: 'center',
  },
  menuButtonOutlined: {
    width: 110,
    height: 90,
    borderWidth: 1.5,
    borderColor: '#57E957',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    backgroundColor: 'transparent',
  },
  menuButtonOutlinedText: {
    color: '#57E957',
    fontWeight: '600',
    fontSize: 13,
    letterSpacing: 1,
    textAlign: 'center',
  },
  menuComponentContainer: {
    backgroundColor: 'black',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuComponentText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 30,
    textAlign: 'center',
  },
  menuBackButton: {
    backgroundColor: '#57E957',
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 8,
  },
  menuBackButtonText: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 1,
    textAlign: 'center',
  },
  pickerContainer: {
    width: '100%',
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#57E957',
    borderRadius: 8,
    marginTop: 8,
    marginBottom: 24,
    justifyContent: 'center',
  },
  picker: {
    color: '#fff',
    width: '100%',
    height: 50,
  },
  backButton: {
    position: 'absolute',
    top: 20,
    left: 20,
    zIndex: 1,
  },
  detalheMotoCard: {
    backgroundColor: '#D9D9D9',
    borderRadius: 8,
    padding: 20,
    alignItems: 'center',
    width: '90%',
    maxWidth: 400,
    marginTop: 20,
  },
  detalheMotoSetorText: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  detalheMotoSetorValue: {
    color: 'black',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  detalheMotoInfoContainer: {
    alignItems: 'center',
  },
  detalheMotoPlaca: {
    color: '#222',
    fontSize: 36,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  detalheMotoModelo: {
    color: '#444',
    fontSize: 18,
    marginBottom: 20,
  },
  detalheMotoImage: {
    width: 200,
    height: 120,
    marginBottom: 20,
    resizeMode: 'contain',
  },

  detalheMotoButton: {
    flexDirection: 'row',
    backgroundColor: '#57E957',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    width: '100%',
  },
  detalheMotoButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 10,
  },
});

export default styles; 